name: frontend_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  
  intl: ^0.19.0
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  http: ^1.2.1
  file_picker: ^8.0.5
  shared_preferences: ^2.2.3
  flutter_staggered_grid_view: ^0.7.0
  intl_phone_field: ^3.2.0
  connectivity_plus: ^2.1.0
  shimmer: ^3.0.0
  event_bus: ^2.0.0
  dropdown_search: ^5.0.6
  mime: ^1.0.5
  http_parser: ^4.0.2
  modal_bottom_sheet: ^3.0.0
  flutter_pdfview: ^1.3.2
  path_provider: ^2.1.3
  syncfusion_flutter_pdfviewer: ^24.2.8
  permission_handler: ^11.3.1
  device_info_plus: ^9.1.2
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.0.7+1
  flutter_launcher_icons: ^0.11.0
  flutter_app_name: ^0.1.1
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/welcome.png
    - assets/images/logo.png
    - assets/lang/id.json
    - assets/lang/en.json

flutter_native_splash:
  color: "#EBF4F6"
  image: assets/images/logo.png
  android: true
  ios: true 
  web: true

flutter_icons:
  android: true
  ios: true
  image_path: assets/images/logo.png

flutter_app_name:
  name: "Orphancare"
